// Copyright 2026 Dicer Authors
// SPDX-License-Identifier: MIT

// Command docgen writes the documentation site's pages that are generated
// from the repository rather than written: the command line reference and
// the daemon's configuration. The API reference is generated by
// protoc-gen-doc instead, with api.md.tmpl; see make docs-gen.
//
// It is run by make docs-gen, and its output is committed.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/konradasb/dicer/internal/cli"
)

// generatedNote heads every generated page's front matter.
const generatedNote = "# Generated by make docs-gen. Do not edit: edit what it is generated from.\n"

func main() {
	repo := flag.String("repo", ".", "The repository's root")
	out := flag.String("out", "docs/content/docs", "The site's content/docs directory")
	flag.Parse()

	if err := run(*repo, *out); err != nil {
		fmt.Fprintf(os.Stderr, "docgen: %v\n", err)
		os.Exit(1)
	}
}

func run(repo, out string) error {
	if err := writeCLI(filepath.Join(out, "reference", "cli")); err != nil {
		return fmt.Errorf("command line: %w", err)
	}
	if err := writeConfig(filepath.Join(repo, "example.yml"), filepath.Join(out, "reference", "configuration.md")); err != nil {
		return fmt.Errorf("configuration: %w", err)
	}
	return nil
}

// writeCLI writes a page for every command into dir, replacing what is
// there: the root command's is the section's index.
func writeCLI(dir string) error {
	root := cli.NewCommand()
	disableAutoGenTag(root)

	tmp, err := os.MkdirTemp("", "docgen-")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(tmp) }()

	link := func(name string) string {
		page := "/docs/reference/cli"
		if p := pageName(strings.TrimSuffix(name, ".md")); p != "_index" {
			page += "/" + p
		}
		return fmt.Sprintf(`{{< relref "%s" >}}`, page)
	}
	if err := doc.GenMarkdownTreeCustom(root, tmp, func(string) string { return "" }, link); err != nil {
		return err
	}

	if err := os.RemoveAll(dir); err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return err
	}

	entries, err := os.ReadDir(tmp)
	if err != nil {
		return err
	}
	for _, e := range entries {
		base := strings.TrimSuffix(e.Name(), ".md")
		body, err := os.ReadFile(filepath.Join(tmp, e.Name()))
		if err != nil {
			return err
		}

		body = dropHeading(body)
		name := pageName(base) + ".md"
		m := meta{title: strings.ReplaceAll(base, "_", " "), description: firstParagraph(body)}
		if base == root.Name() {
			name = "_index.md"
			m = meta{
				title: "Command line", weight: 1, icon: "terminal",
				description: "Every dicer command, with its flags and examples.",
				collapsed:   true,
			}
		}
		if err := writePage(filepath.Join(dir, name), m, body); err != nil {
			return err
		}
	}
	return nil
}

// pageName is the page a command's documentation is written to: the root
// command's is the section's index.
func pageName(base string) string {
	if !strings.Contains(base, "_") {
		return "_index"
	}
	return base
}

// disableAutoGenTag leaves the date out of every page, so that the output
// only changes when the commands do.
func disableAutoGenTag(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, c := range cmd.Commands() {
		disableAutoGenTag(c)
	}
}

// writeConfig writes the daemon's configuration reference: example.yml,
// which shows and explains every key.
func writeConfig(from, to string) error {
	example, err := os.ReadFile(from)
	if err != nil {
		return err
	}

	var body bytes.Buffer
	body.WriteString("`dicerd` reads its configuration from `/etc/dicerd/config.yaml`, or the file\n" +
		"`dicerd serve --config` names. The file is optional: every key has a default,\n" +
		"and unknown keys are rejected.\n\n" +
		"Every key is shown below with its default value.\n\n")
	body.WriteString("```yaml\n")
	body.Write(dropLicense(example))
	body.WriteString("```\n")

	return writePage(to, meta{
		title: "Daemon configuration", weight: 3, icon: "cog",
		description: "Every setting of the daemon, with its default.",
	}, body.Bytes())
}

// meta is a page's front matter. The description and icon are what the
// page's card shows, where a section's index or another page lists it.
type meta struct {
	title       string
	weight      int
	description string
	icon        string

	// collapsed keeps the page's section closed in the sidebar, for one with
	// too many pages to show open.
	collapsed bool
}

// writePage writes a page with front matter.
func writePage(path string, m meta, body []byte) error {
	var page bytes.Buffer
	page.WriteString("---\n" + generatedNote)
	fmt.Fprintf(&page, "title: %q\n", m.title)
	if m.weight > 0 {
		fmt.Fprintf(&page, "weight: %d\n", m.weight)
	}
	if m.description != "" {
		fmt.Fprintf(&page, "description: %q\n", m.description)
	}
	if m.icon != "" {
		fmt.Fprintf(&page, "icon: %s\n", m.icon)
	}
	if m.collapsed {
		page.WriteString("cascade:\n  - params:\n      sidebar:\n        open: false\n")
	}
	page.WriteString("---\n\n")
	page.Write(bytes.TrimLeft(body, "\n"))

	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	return os.WriteFile(path, page.Bytes(), 0o644)
}

// firstParagraph returns a page's first paragraph, joined onto one line: for
// a command, its one-line summary.
func firstParagraph(body []byte) string {
	para, _, _ := bytes.Cut(bytes.TrimLeft(body, "\n"), []byte("\n\n"))
	return strings.Join(strings.Fields(string(para)), " ")
}

// dropHeading removes a document's first heading, which the page's title
// replaces.
func dropHeading(body []byte) []byte {
	first, rest, _ := bytes.Cut(body, []byte("\n"))
	if bytes.HasPrefix(first, []byte("#")) {
		return rest
	}
	return body
}

// dropLicense removes a file's leading licence header and the blank lines
// after it.
func dropLicense(body []byte) []byte {
	for bytes.HasPrefix(body, []byte("# Copyright")) || bytes.HasPrefix(body, []byte("# SPDX")) {
		_, body, _ = bytes.Cut(body, []byte("\n"))
	}
	return bytes.TrimLeft(body, "\n")
}
