// Copyright 2026 Dicer Authors
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: diceragent/v1/diceragent.proto

package diceragentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecStart is the first message sent by the client to start a command.
type ExecStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The command and its arguments. Defaults to /bin/sh.
	Command []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	// Whether to allocate a pseudo-terminal.
	Tty bool `protobuf:"varint,2,opt,name=tty,proto3" json:"tty,omitempty"`
	// The working directory. Defaults to the agent's own.
	Cwd string `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Kills the command after this many seconds. Zero means no limit.
	TimeoutSeconds int32 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// The initial terminal size, when tty is set.
	Rows uint32 `protobuf:"varint,5,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols uint32 `protobuf:"varint,6,opt,name=cols,proto3" json:"cols,omitempty"`
	// Environment variables added to the command's environment.
	Env           map[string]string `protobuf:"bytes,7,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecStart) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecStart) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecStart) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecStart) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecStart) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ExecStart) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ExecStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// ExecResize resizes the remote terminal window.
type ExecResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResize) Reset() {
	*x = ExecResize{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResize) ProtoMessage() {}

func (x *ExecResize) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResize.ProtoReflect.Descriptor instead.
func (*ExecResize) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ExecResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

// ExecRequest is a client-to-server message on the Exec stream.
type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecRequest_Start
	//	*ExecRequest_Stdin
	//	*ExecRequest_Resize
	Payload       isExecRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{2}
}

func (x *ExecRequest) GetPayload() isExecRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecRequest) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Payload.(*ExecRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecRequest) GetResize() *ExecResize {
	if x != nil {
		if x, ok := x.Payload.(*ExecRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isExecRequest_Payload interface {
	isExecRequest_Payload()
}

type ExecRequest_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecRequest_Resize struct {
	Resize *ExecResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*ExecRequest_Start) isExecRequest_Payload() {}

func (*ExecRequest_Stdin) isExecRequest_Payload() {}

func (*ExecRequest_Resize) isExecRequest_Payload() {}

// ExecResponse is a server-to-client message on the Exec stream.
type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecResponse_Stdout
	//	*ExecResponse_Stderr
	//	*ExecResponse_ExitCode
	Payload       isExecResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{3}
}

func (x *ExecResponse) GetPayload() isExecResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Payload.(*ExecResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isExecResponse_Payload interface {
	isExecResponse_Payload()
}

type ExecResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecResponse_ExitCode struct {
	// The command's exit status. Always the last message on the stream.
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*ExecResponse_Stdout) isExecResponse_Payload() {}

func (*ExecResponse_Stderr) isExecResponse_Payload() {}

func (*ExecResponse_ExitCode) isExecResponse_Payload() {}

type CopyInStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where the archive's contents go: into it, if it is a directory; in its
	// place, if it is a file; at it, if nothing is there. A relative path is
	// taken from the root directory.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyInStart) Reset() {
	*x = CopyInStart{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyInStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyInStart) ProtoMessage() {}

func (x *CopyInStart) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyInStart.ProtoReflect.Descriptor instead.
func (*CopyInStart) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{4}
}

func (x *CopyInStart) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CopyInRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CopyInRequest_Start
	//	*CopyInRequest_Data
	Payload       isCopyInRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyInRequest) Reset() {
	*x = CopyInRequest{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyInRequest) ProtoMessage() {}

func (x *CopyInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyInRequest.ProtoReflect.Descriptor instead.
func (*CopyInRequest) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{5}
}

func (x *CopyInRequest) GetPayload() isCopyInRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CopyInRequest) GetStart() *CopyInStart {
	if x != nil {
		if x, ok := x.Payload.(*CopyInRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *CopyInRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*CopyInRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isCopyInRequest_Payload interface {
	isCopyInRequest_Payload()
}

type CopyInRequest_Start struct {
	Start *CopyInStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type CopyInRequest_Data struct {
	// The next chunk of the tar archive.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*CopyInRequest_Start) isCopyInRequest_Payload() {}

func (*CopyInRequest_Data) isCopyInRequest_Payload() {}

type CopyInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyInResponse) Reset() {
	*x = CopyInResponse{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyInResponse) ProtoMessage() {}

func (x *CopyInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyInResponse.ProtoReflect.Descriptor instead.
func (*CopyInResponse) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{6}
}

type CopyOutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The file or directory to read. A relative path is taken from the root
	// directory.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyOutRequest) Reset() {
	*x = CopyOutRequest{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyOutRequest) ProtoMessage() {}

func (x *CopyOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyOutRequest.ProtoReflect.Descriptor instead.
func (*CopyOutRequest) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{7}
}

func (x *CopyOutRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CopyOutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The next chunk of the tar archive.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyOutResponse) Reset() {
	*x = CopyOutResponse{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyOutResponse) ProtoMessage() {}

func (x *CopyOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyOutResponse.ProtoReflect.Descriptor instead.
func (*CopyOutResponse) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{8}
}

func (x *CopyOutResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{9}
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{10}
}

type ProbeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Probe:
	//
	//	*ProbeRequest_Exec
	//	*ProbeRequest_Http
	//	*ProbeRequest_Tcp
	Probe isProbeRequest_Probe `protobuf_oneof:"probe"`
	// How long the probe may take. A probe that overruns has failed.
	Timeout       *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{11}
}

func (x *ProbeRequest) GetProbe() isProbeRequest_Probe {
	if x != nil {
		return x.Probe
	}
	return nil
}

func (x *ProbeRequest) GetExec() *ExecProbe {
	if x != nil {
		if x, ok := x.Probe.(*ProbeRequest_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *ProbeRequest) GetHttp() *HTTPProbe {
	if x != nil {
		if x, ok := x.Probe.(*ProbeRequest_Http); ok {
			return x.Http
		}
	}
	return nil
}

func (x *ProbeRequest) GetTcp() *TCPProbe {
	if x != nil {
		if x, ok := x.Probe.(*ProbeRequest_Tcp); ok {
			return x.Tcp
		}
	}
	return nil
}

func (x *ProbeRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type isProbeRequest_Probe interface {
	isProbeRequest_Probe()
}

type ProbeRequest_Exec struct {
	Exec *ExecProbe `protobuf:"bytes,1,opt,name=exec,proto3,oneof"`
}

type ProbeRequest_Http struct {
	Http *HTTPProbe `protobuf:"bytes,2,opt,name=http,proto3,oneof"`
}

type ProbeRequest_Tcp struct {
	Tcp *TCPProbe `protobuf:"bytes,3,opt,name=tcp,proto3,oneof"`
}

func (*ProbeRequest_Exec) isProbeRequest_Probe() {}

func (*ProbeRequest_Http) isProbeRequest_Probe() {}

func (*ProbeRequest_Tcp) isProbeRequest_Probe() {}

// ExecProbe passes when the command exits 0.
type ExecProbe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecProbe) Reset() {
	*x = ExecProbe{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecProbe) ProtoMessage() {}

func (x *ExecProbe) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecProbe.ProtoReflect.Descriptor instead.
func (*ExecProbe) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{12}
}

func (x *ExecProbe) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

// HTTPProbe passes when a GET of path on port, on the loopback address,
// answers with a 2xx or 3xx status. Redirects are not followed.
type HTTPProbe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Port  uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// Defaults to /.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPProbe) Reset() {
	*x = HTTPProbe{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPProbe) ProtoMessage() {}

func (x *HTTPProbe) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPProbe.ProtoReflect.Descriptor instead.
func (*HTTPProbe) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{13}
}

func (x *HTTPProbe) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HTTPProbe) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// TCPProbe passes when a connection to port, on the loopback address, opens.
type TCPProbe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPProbe) Reset() {
	*x = TCPProbe{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPProbe) ProtoMessage() {}

func (x *TCPProbe) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPProbe.ProtoReflect.Descriptor instead.
func (*TCPProbe) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{14}
}

func (x *TCPProbe) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ProbeResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Healthy bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// What the probe said: a command's output, an HTTP status, or why it
	// failed. Truncated.
	Output        string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{15}
}

func (x *ProbeResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ProbeResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{16}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diceragent_v1_diceragent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_diceragent_v1_diceragent_proto_rawDescGZIP(), []int{17}
}

var File_diceragent_v1_diceragent_proto protoreflect.FileDescriptor

const file_diceragent_v1_diceragent_proto_rawDesc = "" +
	"\n" +
	"\x1ediceragent/v1/diceragent.proto\x12\rdiceragent.v1\x1a\x1egoogle/protobuf/duration.proto\"\x87\x02\n" +
	"\tExecStart\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12\x10\n" +
	"\x03tty\x18\x02 \x01(\bR\x03tty\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12\x12\n" +
	"\x04rows\x18\x05 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x06 \x01(\rR\x04cols\x123\n" +
	"\x03env\x18\a \x03(\v2!.diceragent.v1.ExecStart.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\n" +
	"ExecResize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\"\x97\x01\n" +
	"\vExecRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x18.diceragent.v1.ExecStartH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x123\n" +
	"\x06resize\x18\x03 \x01(\v2\x19.diceragent.v1.ExecResizeH\x00R\x06resizeB\t\n" +
	"\apayload\"l\n" +
	"\fExecResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x1d\n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCodeB\t\n" +
	"\apayload\"!\n" +
	"\vCopyInStart\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"d\n" +
	"\rCopyInRequest\x122\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.diceragent.v1.CopyInStartH\x00R\x05start\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\x10\n" +
	"\x0eCopyInResponse\"$\n" +
	"\x0eCopyOutRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"%\n" +
	"\x0fCopyOutResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\r\n" +
	"\vSyncRequest\"\x0e\n" +
	"\fSyncResponse\"\xd9\x01\n" +
	"\fProbeRequest\x12.\n" +
	"\x04exec\x18\x01 \x01(\v2\x18.diceragent.v1.ExecProbeH\x00R\x04exec\x12.\n" +
	"\x04http\x18\x02 \x01(\v2\x18.diceragent.v1.HTTPProbeH\x00R\x04http\x12+\n" +
	"\x03tcp\x18\x03 \x01(\v2\x17.diceragent.v1.TCPProbeH\x00R\x03tcp\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeoutB\a\n" +
	"\x05probe\"%\n" +
	"\tExecProbe\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\"3\n" +
	"\tHTTPProbe\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x1e\n" +
	"\bTCPProbe\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\"A\n" +
	"\rProbeResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse2\xba\x03\n" +
	"\fAgentService\x12C\n" +
	"\x04Exec\x12\x1a.diceragent.v1.ExecRequest\x1a\x1b.diceragent.v1.ExecResponse(\x010\x01\x12G\n" +
	"\x06CopyIn\x12\x1c.diceragent.v1.CopyInRequest\x1a\x1d.diceragent.v1.CopyInResponse(\x01\x12J\n" +
	"\aCopyOut\x12\x1d.diceragent.v1.CopyOutRequest\x1a\x1e.diceragent.v1.CopyOutResponse0\x01\x12?\n" +
	"\x04Sync\x12\x1a.diceragent.v1.SyncRequest\x1a\x1b.diceragent.v1.SyncResponse\x12B\n" +
	"\x05Probe\x12\x1b.diceragent.v1.ProbeRequest\x1a\x1c.diceragent.v1.ProbeResponse\x12K\n" +
	"\bShutdown\x12\x1e.diceragent.v1.ShutdownRequest\x1a\x1f.diceragent.v1.ShutdownResponseB<Z:github.com/dicer-sh/dicer/proto/diceragent/v1;diceragentv1b\x06proto3"

var (
	file_diceragent_v1_diceragent_proto_rawDescOnce sync.Once
	file_diceragent_v1_diceragent_proto_rawDescData []byte
)

func file_diceragent_v1_diceragent_proto_rawDescGZIP() []byte {
	file_diceragent_v1_diceragent_proto_rawDescOnce.Do(func() {
		file_diceragent_v1_diceragent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diceragent_v1_diceragent_proto_rawDesc), len(file_diceragent_v1_diceragent_proto_rawDesc)))
	})
	return file_diceragent_v1_diceragent_proto_rawDescData
}

var file_diceragent_v1_diceragent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_diceragent_v1_diceragent_proto_goTypes = []any{
	(*ExecStart)(nil),           // 0: diceragent.v1.ExecStart
	(*ExecResize)(nil),          // 1: diceragent.v1.ExecResize
	(*ExecRequest)(nil),         // 2: diceragent.v1.ExecRequest
	(*ExecResponse)(nil),        // 3: diceragent.v1.ExecResponse
	(*CopyInStart)(nil),         // 4: diceragent.v1.CopyInStart
	(*CopyInRequest)(nil),       // 5: diceragent.v1.CopyInRequest
	(*CopyInResponse)(nil),      // 6: diceragent.v1.CopyInResponse
	(*CopyOutRequest)(nil),      // 7: diceragent.v1.CopyOutRequest
	(*CopyOutResponse)(nil),     // 8: diceragent.v1.CopyOutResponse
	(*SyncRequest)(nil),         // 9: diceragent.v1.SyncRequest
	(*SyncResponse)(nil),        // 10: diceragent.v1.SyncResponse
	(*ProbeRequest)(nil),        // 11: diceragent.v1.ProbeRequest
	(*ExecProbe)(nil),           // 12: diceragent.v1.ExecProbe
	(*HTTPProbe)(nil),           // 13: diceragent.v1.HTTPProbe
	(*TCPProbe)(nil),            // 14: diceragent.v1.TCPProbe
	(*ProbeResponse)(nil),       // 15: diceragent.v1.ProbeResponse
	(*ShutdownRequest)(nil),     // 16: diceragent.v1.ShutdownRequest
	(*ShutdownResponse)(nil),    // 17: diceragent.v1.ShutdownResponse
	nil,                         // 18: diceragent.v1.ExecStart.EnvEntry
	(*durationpb.Duration)(nil), // 19: google.protobuf.Duration
}
var file_diceragent_v1_diceragent_proto_depIdxs = []int32{
	18, // 0: diceragent.v1.ExecStart.env:type_name -> diceragent.v1.ExecStart.EnvEntry
	0,  // 1: diceragent.v1.ExecRequest.start:type_name -> diceragent.v1.ExecStart
	1,  // 2: diceragent.v1.ExecRequest.resize:type_name -> diceragent.v1.ExecResize
	4,  // 3: diceragent.v1.CopyInRequest.start:type_name -> diceragent.v1.CopyInStart
	12, // 4: diceragent.v1.ProbeRequest.exec:type_name -> diceragent.v1.ExecProbe
	13, // 5: diceragent.v1.ProbeRequest.http:type_name -> diceragent.v1.HTTPProbe
	14, // 6: diceragent.v1.ProbeRequest.tcp:type_name -> diceragent.v1.TCPProbe
	19, // 7: diceragent.v1.ProbeRequest.timeout:type_name -> google.protobuf.Duration
	2,  // 8: diceragent.v1.AgentService.Exec:input_type -> diceragent.v1.ExecRequest
	5,  // 9: diceragent.v1.AgentService.CopyIn:input_type -> diceragent.v1.CopyInRequest
	7,  // 10: diceragent.v1.AgentService.CopyOut:input_type -> diceragent.v1.CopyOutRequest
	9,  // 11: diceragent.v1.AgentService.Sync:input_type -> diceragent.v1.SyncRequest
	11, // 12: diceragent.v1.AgentService.Probe:input_type -> diceragent.v1.ProbeRequest
	16, // 13: diceragent.v1.AgentService.Shutdown:input_type -> diceragent.v1.ShutdownRequest
	3,  // 14: diceragent.v1.AgentService.Exec:output_type -> diceragent.v1.ExecResponse
	6,  // 15: diceragent.v1.AgentService.CopyIn:output_type -> diceragent.v1.CopyInResponse
	8,  // 16: diceragent.v1.AgentService.CopyOut:output_type -> diceragent.v1.CopyOutResponse
	10, // 17: diceragent.v1.AgentService.Sync:output_type -> diceragent.v1.SyncResponse
	15, // 18: diceragent.v1.AgentService.Probe:output_type -> diceragent.v1.ProbeResponse
	17, // 19: diceragent.v1.AgentService.Shutdown:output_type -> diceragent.v1.ShutdownResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_diceragent_v1_diceragent_proto_init() }
func file_diceragent_v1_diceragent_proto_init() {
	if File_diceragent_v1_diceragent_proto != nil {
		return
	}
	file_diceragent_v1_diceragent_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecRequest_Start)(nil),
		(*ExecRequest_Stdin)(nil),
		(*ExecRequest_Resize)(nil),
	}
	file_diceragent_v1_diceragent_proto_msgTypes[3].OneofWrappers = []any{
		(*ExecResponse_Stdout)(nil),
		(*ExecResponse_Stderr)(nil),
		(*ExecResponse_ExitCode)(nil),
	}
	file_diceragent_v1_diceragent_proto_msgTypes[5].OneofWrappers = []any{
		(*CopyInRequest_Start)(nil),
		(*CopyInRequest_Data)(nil),
	}
	file_diceragent_v1_diceragent_proto_msgTypes[11].OneofWrappers = []any{
		(*ProbeRequest_Exec)(nil),
		(*ProbeRequest_Http)(nil),
		(*ProbeRequest_Tcp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diceragent_v1_diceragent_proto_rawDesc), len(file_diceragent_v1_diceragent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diceragent_v1_diceragent_proto_goTypes,
		DependencyIndexes: file_diceragent_v1_diceragent_proto_depIdxs,
		MessageInfos:      file_diceragent_v1_diceragent_proto_msgTypes,
	}.Build()
	File_diceragent_v1_diceragent_proto = out.File
	file_diceragent_v1_diceragent_proto_goTypes = nil
	file_diceragent_v1_diceragent_proto_depIdxs = nil
}
