// Copyright 2026 Dicer Authors
// SPDX-License-Identifier: MIT

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dicerd/v1/dicerd.proto

package dicerdv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_CreateInstance_FullMethodName         = "/dicerd.v1.DaemonService/CreateInstance"
	DaemonService_UpdateInstance_FullMethodName         = "/dicerd.v1.DaemonService/UpdateInstance"
	DaemonService_RenameInstance_FullMethodName         = "/dicerd.v1.DaemonService/RenameInstance"
	DaemonService_StartInstance_FullMethodName          = "/dicerd.v1.DaemonService/StartInstance"
	DaemonService_StopInstance_FullMethodName           = "/dicerd.v1.DaemonService/StopInstance"
	DaemonService_PauseInstance_FullMethodName          = "/dicerd.v1.DaemonService/PauseInstance"
	DaemonService_ResumeInstance_FullMethodName         = "/dicerd.v1.DaemonService/ResumeInstance"
	DaemonService_DeleteInstance_FullMethodName         = "/dicerd.v1.DaemonService/DeleteInstance"
	DaemonService_ListInstances_FullMethodName          = "/dicerd.v1.DaemonService/ListInstances"
	DaemonService_GetInstance_FullMethodName            = "/dicerd.v1.DaemonService/GetInstance"
	DaemonService_GetInstanceLogs_FullMethodName        = "/dicerd.v1.DaemonService/GetInstanceLogs"
	DaemonService_CreateSnapshot_FullMethodName         = "/dicerd.v1.DaemonService/CreateSnapshot"
	DaemonService_ListSnapshots_FullMethodName          = "/dicerd.v1.DaemonService/ListSnapshots"
	DaemonService_GetSnapshot_FullMethodName            = "/dicerd.v1.DaemonService/GetSnapshot"
	DaemonService_DeleteSnapshot_FullMethodName         = "/dicerd.v1.DaemonService/DeleteSnapshot"
	DaemonService_RestoreSnapshot_FullMethodName        = "/dicerd.v1.DaemonService/RestoreSnapshot"
	DaemonService_ExecInstance_FullMethodName           = "/dicerd.v1.DaemonService/ExecInstance"
	DaemonService_CopyToInstance_FullMethodName         = "/dicerd.v1.DaemonService/CopyToInstance"
	DaemonService_CopyFromInstance_FullMethodName       = "/dicerd.v1.DaemonService/CopyFromInstance"
	DaemonService_CreateNetwork_FullMethodName          = "/dicerd.v1.DaemonService/CreateNetwork"
	DaemonService_ListNetworks_FullMethodName           = "/dicerd.v1.DaemonService/ListNetworks"
	DaemonService_GetNetwork_FullMethodName             = "/dicerd.v1.DaemonService/GetNetwork"
	DaemonService_DeleteNetwork_FullMethodName          = "/dicerd.v1.DaemonService/DeleteNetwork"
	DaemonService_ListNetworkAllocations_FullMethodName = "/dicerd.v1.DaemonService/ListNetworkAllocations"
	DaemonService_CreateVolume_FullMethodName           = "/dicerd.v1.DaemonService/CreateVolume"
	DaemonService_ListVolumes_FullMethodName            = "/dicerd.v1.DaemonService/ListVolumes"
	DaemonService_GetVolume_FullMethodName              = "/dicerd.v1.DaemonService/GetVolume"
	DaemonService_DeleteVolume_FullMethodName           = "/dicerd.v1.DaemonService/DeleteVolume"
	DaemonService_PullImage_FullMethodName              = "/dicerd.v1.DaemonService/PullImage"
	DaemonService_ListImages_FullMethodName             = "/dicerd.v1.DaemonService/ListImages"
	DaemonService_GetImage_FullMethodName               = "/dicerd.v1.DaemonService/GetImage"
	DaemonService_DeleteImage_FullMethodName            = "/dicerd.v1.DaemonService/DeleteImage"
	DaemonService_PruneImages_FullMethodName            = "/dicerd.v1.DaemonService/PruneImages"
	DaemonService_ImportKernel_FullMethodName           = "/dicerd.v1.DaemonService/ImportKernel"
	DaemonService_ListKernels_FullMethodName            = "/dicerd.v1.DaemonService/ListKernels"
	DaemonService_GetKernel_FullMethodName              = "/dicerd.v1.DaemonService/GetKernel"
	DaemonService_DeleteKernel_FullMethodName           = "/dicerd.v1.DaemonService/DeleteKernel"
	DaemonService_GetHostInfo_FullMethodName            = "/dicerd.v1.DaemonService/GetHostInfo"
	DaemonService_GetResources_FullMethodName           = "/dicerd.v1.DaemonService/GetResources"
	DaemonService_GetEvents_FullMethodName              = "/dicerd.v1.DaemonService/GetEvents"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DaemonService manages virtual machines on a single host.
//
// There is no notion of a cluster, a node or placement: the daemon owns the
// machine it runs on. To manage several hosts, run a daemon on each and point
// a client at whichever one you mean.
//
// Creating an instance records its definition; it does not boot it. Use
// StartInstance for that. The two are separate so a definition can be written,
// reviewed and version-controlled before anything runs.
//
// Resources are addressed by name or ID wherever a request has a name field.
// Methods follow the resource-oriented design of https://google.aip.dev:
// standard methods return the resource they act on, and deletes return Empty.
//
// A failed call ends with a status whose code says what kind of failure it
// was, and whose message says it for a person:
//
//   - `NOT_FOUND`: the resource named does not exist.
//   - `ALREADY_EXISTS`: a resource with that name exists already.
//   - `INVALID_ARGUMENT`: the request is malformed, whatever the host's state.
//   - `FAILED_PRECONDITION`: the resource is in the wrong state for the call,
//     such as deleting a running instance.
//   - `RESOURCE_EXHAUSTED`: the host has too little left: CPU or memory for an
//     instance, addresses on a network.
//   - `UNAVAILABLE`: something the daemon needs cannot be reached: a registry,
//     a guest's agent. Trying again may work.
//   - `PERMISSION_DENIED`: the guest refused, such as a file it protects.
//   - `UNIMPLEMENTED`: the daemon, or an instance's guest agent, is too old for
//     the call.
//   - `INTERNAL`: anything else: the daemon failed.
type DaemonServiceClient interface {
	// CreateInstance records an instance definition without starting it,
	// unless start is set.
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*Instance, error)
	// UpdateInstance modifies the definition of a stopped instance.
	UpdateInstance(ctx context.Context, in *UpdateInstanceRequest, opts ...grpc.CallOption) (*Instance, error)
	// RenameInstance changes a stopped instance's name. The instance keeps its
	// ID, its disks and its address; only what people call it changes.
	RenameInstance(ctx context.Context, in *RenameInstanceRequest, opts ...grpc.CallOption) (*Instance, error)
	// StartInstance boots a defined instance.
	StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*Instance, error)
	// StopInstance shuts a running instance down, keeping its definition,
	// overlay disk and address.
	StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (*Instance, error)
	// PauseInstance halts a running instance's vCPUs, keeping it resident.
	PauseInstance(ctx context.Context, in *PauseInstanceRequest, opts ...grpc.CallOption) (*Instance, error)
	// ResumeInstance continues a paused instance.
	ResumeInstance(ctx context.Context, in *ResumeInstanceRequest, opts ...grpc.CallOption) (*Instance, error)
	// DeleteInstance removes an instance and its overlay disk. It refuses a
	// running instance unless force is set.
	DeleteInstance(ctx context.Context, in *DeleteInstanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListInstances returns every defined instance.
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	// GetInstance returns one instance.
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*Instance, error)
	// GetInstanceLogs streams an instance's log. The guest's console is kept
	// with the instance, so it can be read after a stop to explain one.
	GetInstanceLogs(ctx context.Context, in *GetInstanceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceLogChunk], error)
	// CreateSnapshot freezes a running or paused instance to disk: its memory,
	// its device state and a copy of its overlay disk. A running instance is
	// paused for as long as it takes and resumed afterwards.
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error)
	// ListSnapshots returns an instance's snapshots, oldest first.
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	// GetSnapshot returns one snapshot.
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error)
	// DeleteSnapshot removes a snapshot.
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RestoreSnapshot puts a stopped instance back to the moment a snapshot
	// was taken and resumes it. Anything written to its disk since is
	// discarded.
	RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*Instance, error)
	// ExecInstance runs a command inside a running instance. The first client
	// message must be an ExecInstanceStart; subsequent messages carry stdin data
	// or terminal resize events.
	ExecInstance(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInstanceRequest, ExecInstanceResponse], error)
	// CopyToInstance writes a file or directory into a running instance. The
	// first message must be a CopyToInstanceStart; the rest carry a tar
	// archive of it, in chunks, which lands at the path as cp would put it.
	CopyToInstance(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CopyToInstanceRequest, emptypb.Empty], error)
	// CopyFromInstance reads a file or directory out of a running instance, as
	// a tar archive in chunks.
	CopyFromInstance(ctx context.Context, in *CopyFromInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CopyFromInstanceResponse], error)
	// CreateNetwork defines a host-local network. Its bridge is brought up
	// when the first instance on it starts.
	CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*Network, error)
	// ListNetworks returns every network.
	ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error)
	// GetNetwork returns one network.
	GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*Network, error)
	// DeleteNetwork removes a network that no instance references.
	DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListNetworkAllocations reports which addresses are assigned on a network.
	// Allocation itself is a side effect of starting an instance and has no
	// separate RPC.
	ListNetworkAllocations(ctx context.Context, in *ListNetworkAllocationsRequest, opts ...grpc.CallOption) (*ListNetworkAllocationsResponse, error)
	// CreateVolume provisions a persistent block volume.
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*Volume, error)
	// ListVolumes returns every volume.
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	// GetVolume returns one volume.
	GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*Volume, error)
	// DeleteVolume removes a volume that no instance references.
	DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// PullImage fetches an OCI image and converts it to a bootable root
	// filesystem, reporting progress as it goes. The last message carries the
	// image, which is ready to boot.
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullImageProgress], error)
	// ListImages returns every pulled image.
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	// GetImage returns one pulled image.
	GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*Image, error)
	// DeleteImage removes a pulled image. It refuses an image an instance is
	// defined to boot from, unless force is set.
	DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// PruneImages removes every image no instance is defined to boot from.
	PruneImages(ctx context.Context, in *PruneImagesRequest, opts ...grpc.CallOption) (*PruneImagesResponse, error)
	// ImportKernel records a guest kernel by URL. It is downloaded the first
	// time an instance boots with it.
	ImportKernel(ctx context.Context, in *ImportKernelRequest, opts ...grpc.CallOption) (*Kernel, error)
	// ListKernels returns every imported kernel.
	ListKernels(ctx context.Context, in *ListKernelsRequest, opts ...grpc.CallOption) (*ListKernelsResponse, error)
	// GetKernel returns one kernel.
	GetKernel(ctx context.Context, in *GetKernelRequest, opts ...grpc.CallOption) (*Kernel, error)
	// DeleteKernel removes a kernel that no instance references.
	DeleteKernel(ctx context.Context, in *DeleteKernelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetHostInfo reports what the daemon is: its version, the hypervisors it
	// carries, and how it is reached.
	GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*GetHostInfoResponse, error)
	// GetResources reports how much CPU and memory instances may be given,
	// how much they hold, and how full the data directory's disk is.
	GetResources(ctx context.Context, in *GetResourcesRequest, opts ...grpc.CallOption) (*GetResourcesResponse, error)
	// GetEvents streams what has happened to the resources on this host: the
	// history kept, oldest first, in batches, then, with follow, each new
	// event as it happens, none missed between the two. A follower that does
	// not keep up is disconnected with RESOURCE_EXHAUSTED rather than slowing
	// the host.
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetEventsResponse], error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*Instance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Instance)
	err := c.cc.Invoke(ctx, DaemonService_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) UpdateInstance(ctx context.Context, in *UpdateInstanceRequest, opts ...grpc.CallOption) (*Instance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Instance)
	err := c.cc.Invoke(ctx, DaemonService_UpdateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RenameInstance(ctx context.Context, in *RenameInstanceRequest, opts ...grpc.CallOption) (*Instance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Instance)
	err := c.cc.Invoke(ctx, DaemonService_RenameInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*Instance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Instance)
	err := c.cc.Invoke(ctx, DaemonService_StartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (*Instance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Instance)
	err := c.cc.Invoke(ctx, DaemonService_StopInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) PauseInstance(ctx context.Context, in *PauseInstanceRequest, opts ...grpc.CallOption) (*Instance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Instance)
	err := c.cc.Invoke(ctx, DaemonService_PauseInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ResumeInstance(ctx context.Context, in *ResumeInstanceRequest, opts ...grpc.CallOption) (*Instance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Instance)
	err := c.cc.Invoke(ctx, DaemonService_ResumeInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteInstance(ctx context.Context, in *DeleteInstanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DaemonService_DeleteInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstancesResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*Instance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Instance)
	err := c.cc.Invoke(ctx, DaemonService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetInstanceLogs(ctx context.Context, in *GetInstanceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceLogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[0], DaemonService_GetInstanceLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetInstanceLogsRequest, InstanceLogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_GetInstanceLogsClient = grpc.ServerStreamingClient[InstanceLogChunk]

func (c *daemonServiceClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, DaemonService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, DaemonService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DaemonService_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*Instance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Instance)
	err := c.cc.Invoke(ctx, DaemonService_RestoreSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ExecInstance(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInstanceRequest, ExecInstanceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[1], DaemonService_ExecInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecInstanceRequest, ExecInstanceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_ExecInstanceClient = grpc.BidiStreamingClient[ExecInstanceRequest, ExecInstanceResponse]

func (c *daemonServiceClient) CopyToInstance(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CopyToInstanceRequest, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[2], DaemonService_CopyToInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyToInstanceRequest, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_CopyToInstanceClient = grpc.ClientStreamingClient[CopyToInstanceRequest, emptypb.Empty]

func (c *daemonServiceClient) CopyFromInstance(ctx context.Context, in *CopyFromInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CopyFromInstanceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[3], DaemonService_CopyFromInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyFromInstanceRequest, CopyFromInstanceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_CopyFromInstanceClient = grpc.ServerStreamingClient[CopyFromInstanceResponse]

func (c *daemonServiceClient) CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*Network, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Network)
	err := c.cc.Invoke(ctx, DaemonService_CreateNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworksResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*Network, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Network)
	err := c.cc.Invoke(ctx, DaemonService_GetNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DaemonService_DeleteNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListNetworkAllocations(ctx context.Context, in *ListNetworkAllocationsRequest, opts ...grpc.CallOption) (*ListNetworkAllocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworkAllocationsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListNetworkAllocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*Volume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Volume)
	err := c.cc.Invoke(ctx, DaemonService_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*Volume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Volume)
	err := c.cc.Invoke(ctx, DaemonService_GetVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DaemonService_DeleteVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullImageProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[4], DaemonService_PullImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullImageRequest, PullImageProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_PullImageClient = grpc.ServerStreamingClient[PullImageProgress]

func (c *daemonServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, DaemonService_GetImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DaemonService_DeleteImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) PruneImages(ctx context.Context, in *PruneImagesRequest, opts ...grpc.CallOption) (*PruneImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PruneImagesResponse)
	err := c.cc.Invoke(ctx, DaemonService_PruneImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ImportKernel(ctx context.Context, in *ImportKernelRequest, opts ...grpc.CallOption) (*Kernel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Kernel)
	err := c.cc.Invoke(ctx, DaemonService_ImportKernel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListKernels(ctx context.Context, in *ListKernelsRequest, opts ...grpc.CallOption) (*ListKernelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKernelsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListKernels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetKernel(ctx context.Context, in *GetKernelRequest, opts ...grpc.CallOption) (*Kernel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Kernel)
	err := c.cc.Invoke(ctx, DaemonService_GetKernel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteKernel(ctx context.Context, in *DeleteKernelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DaemonService_DeleteKernel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*GetHostInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostInfoResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetHostInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetResources(ctx context.Context, in *GetResourcesRequest, opts ...grpc.CallOption) (*GetResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourcesResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[5], DaemonService_GetEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetEventsRequest, GetEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_GetEventsClient = grpc.ServerStreamingClient[GetEventsResponse]

// DaemonServiceServer is the server API for DaemonService service.
// All implementations should embed UnimplementedDaemonServiceServer
// for forward compatibility.
//
// DaemonService manages virtual machines on a single host.
//
// There is no notion of a cluster, a node or placement: the daemon owns the
// machine it runs on. To manage several hosts, run a daemon on each and point
// a client at whichever one you mean.
//
// Creating an instance records its definition; it does not boot it. Use
// StartInstance for that. The two are separate so a definition can be written,
// reviewed and version-controlled before anything runs.
//
// Resources are addressed by name or ID wherever a request has a name field.
// Methods follow the resource-oriented design of https://google.aip.dev:
// standard methods return the resource they act on, and deletes return Empty.
//
// A failed call ends with a status whose code says what kind of failure it
// was, and whose message says it for a person:
//
//   - `NOT_FOUND`: the resource named does not exist.
//   - `ALREADY_EXISTS`: a resource with that name exists already.
//   - `INVALID_ARGUMENT`: the request is malformed, whatever the host's state.
//   - `FAILED_PRECONDITION`: the resource is in the wrong state for the call,
//     such as deleting a running instance.
//   - `RESOURCE_EXHAUSTED`: the host has too little left: CPU or memory for an
//     instance, addresses on a network.
//   - `UNAVAILABLE`: something the daemon needs cannot be reached: a registry,
//     a guest's agent. Trying again may work.
//   - `PERMISSION_DENIED`: the guest refused, such as a file it protects.
//   - `UNIMPLEMENTED`: the daemon, or an instance's guest agent, is too old for
//     the call.
//   - `INTERNAL`: anything else: the daemon failed.
type DaemonServiceServer interface {
	// CreateInstance records an instance definition without starting it,
	// unless start is set.
	CreateInstance(context.Context, *CreateInstanceRequest) (*Instance, error)
	// UpdateInstance modifies the definition of a stopped instance.
	UpdateInstance(context.Context, *UpdateInstanceRequest) (*Instance, error)
	// RenameInstance changes a stopped instance's name. The instance keeps its
	// ID, its disks and its address; only what people call it changes.
	RenameInstance(context.Context, *RenameInstanceRequest) (*Instance, error)
	// StartInstance boots a defined instance.
	StartInstance(context.Context, *StartInstanceRequest) (*Instance, error)
	// StopInstance shuts a running instance down, keeping its definition,
	// overlay disk and address.
	StopInstance(context.Context, *StopInstanceRequest) (*Instance, error)
	// PauseInstance halts a running instance's vCPUs, keeping it resident.
	PauseInstance(context.Context, *PauseInstanceRequest) (*Instance, error)
	// ResumeInstance continues a paused instance.
	ResumeInstance(context.Context, *ResumeInstanceRequest) (*Instance, error)
	// DeleteInstance removes an instance and its overlay disk. It refuses a
	// running instance unless force is set.
	DeleteInstance(context.Context, *DeleteInstanceRequest) (*emptypb.Empty, error)
	// ListInstances returns every defined instance.
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	// GetInstance returns one instance.
	GetInstance(context.Context, *GetInstanceRequest) (*Instance, error)
	// GetInstanceLogs streams an instance's log. The guest's console is kept
	// with the instance, so it can be read after a stop to explain one.
	GetInstanceLogs(*GetInstanceLogsRequest, grpc.ServerStreamingServer[InstanceLogChunk]) error
	// CreateSnapshot freezes a running or paused instance to disk: its memory,
	// its device state and a copy of its overlay disk. A running instance is
	// paused for as long as it takes and resumed afterwards.
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*Snapshot, error)
	// ListSnapshots returns an instance's snapshots, oldest first.
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	// GetSnapshot returns one snapshot.
	GetSnapshot(context.Context, *GetSnapshotRequest) (*Snapshot, error)
	// DeleteSnapshot removes a snapshot.
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*emptypb.Empty, error)
	// RestoreSnapshot puts a stopped instance back to the moment a snapshot
	// was taken and resumes it. Anything written to its disk since is
	// discarded.
	RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*Instance, error)
	// ExecInstance runs a command inside a running instance. The first client
	// message must be an ExecInstanceStart; subsequent messages carry stdin data
	// or terminal resize events.
	ExecInstance(grpc.BidiStreamingServer[ExecInstanceRequest, ExecInstanceResponse]) error
	// CopyToInstance writes a file or directory into a running instance. The
	// first message must be a CopyToInstanceStart; the rest carry a tar
	// archive of it, in chunks, which lands at the path as cp would put it.
	CopyToInstance(grpc.ClientStreamingServer[CopyToInstanceRequest, emptypb.Empty]) error
	// CopyFromInstance reads a file or directory out of a running instance, as
	// a tar archive in chunks.
	CopyFromInstance(*CopyFromInstanceRequest, grpc.ServerStreamingServer[CopyFromInstanceResponse]) error
	// CreateNetwork defines a host-local network. Its bridge is brought up
	// when the first instance on it starts.
	CreateNetwork(context.Context, *CreateNetworkRequest) (*Network, error)
	// ListNetworks returns every network.
	ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error)
	// GetNetwork returns one network.
	GetNetwork(context.Context, *GetNetworkRequest) (*Network, error)
	// DeleteNetwork removes a network that no instance references.
	DeleteNetwork(context.Context, *DeleteNetworkRequest) (*emptypb.Empty, error)
	// ListNetworkAllocations reports which addresses are assigned on a network.
	// Allocation itself is a side effect of starting an instance and has no
	// separate RPC.
	ListNetworkAllocations(context.Context, *ListNetworkAllocationsRequest) (*ListNetworkAllocationsResponse, error)
	// CreateVolume provisions a persistent block volume.
	CreateVolume(context.Context, *CreateVolumeRequest) (*Volume, error)
	// ListVolumes returns every volume.
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	// GetVolume returns one volume.
	GetVolume(context.Context, *GetVolumeRequest) (*Volume, error)
	// DeleteVolume removes a volume that no instance references.
	DeleteVolume(context.Context, *DeleteVolumeRequest) (*emptypb.Empty, error)
	// PullImage fetches an OCI image and converts it to a bootable root
	// filesystem, reporting progress as it goes. The last message carries the
	// image, which is ready to boot.
	PullImage(*PullImageRequest, grpc.ServerStreamingServer[PullImageProgress]) error
	// ListImages returns every pulled image.
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	// GetImage returns one pulled image.
	GetImage(context.Context, *GetImageRequest) (*Image, error)
	// DeleteImage removes a pulled image. It refuses an image an instance is
	// defined to boot from, unless force is set.
	DeleteImage(context.Context, *DeleteImageRequest) (*emptypb.Empty, error)
	// PruneImages removes every image no instance is defined to boot from.
	PruneImages(context.Context, *PruneImagesRequest) (*PruneImagesResponse, error)
	// ImportKernel records a guest kernel by URL. It is downloaded the first
	// time an instance boots with it.
	ImportKernel(context.Context, *ImportKernelRequest) (*Kernel, error)
	// ListKernels returns every imported kernel.
	ListKernels(context.Context, *ListKernelsRequest) (*ListKernelsResponse, error)
	// GetKernel returns one kernel.
	GetKernel(context.Context, *GetKernelRequest) (*Kernel, error)
	// DeleteKernel removes a kernel that no instance references.
	DeleteKernel(context.Context, *DeleteKernelRequest) (*emptypb.Empty, error)
	// GetHostInfo reports what the daemon is: its version, the hypervisors it
	// carries, and how it is reached.
	GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error)
	// GetResources reports how much CPU and memory instances may be given,
	// how much they hold, and how full the data directory's disk is.
	GetResources(context.Context, *GetResourcesRequest) (*GetResourcesResponse, error)
	// GetEvents streams what has happened to the resources on this host: the
	// history kept, oldest first, in batches, then, with follow, each new
	// event as it happens, none missed between the two. A follower that does
	// not keep up is disconnected with RESOURCE_EXHAUSTED rather than slowing
	// the host.
	GetEvents(*GetEventsRequest, grpc.ServerStreamingServer[GetEventsResponse]) error
}

// UnimplementedDaemonServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*Instance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedDaemonServiceServer) UpdateInstance(context.Context, *UpdateInstanceRequest) (*Instance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInstance not implemented")
}
func (UnimplementedDaemonServiceServer) RenameInstance(context.Context, *RenameInstanceRequest) (*Instance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameInstance not implemented")
}
func (UnimplementedDaemonServiceServer) StartInstance(context.Context, *StartInstanceRequest) (*Instance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedDaemonServiceServer) StopInstance(context.Context, *StopInstanceRequest) (*Instance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopInstance not implemented")
}
func (UnimplementedDaemonServiceServer) PauseInstance(context.Context, *PauseInstanceRequest) (*Instance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseInstance not implemented")
}
func (UnimplementedDaemonServiceServer) ResumeInstance(context.Context, *ResumeInstanceRequest) (*Instance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeInstance not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteInstance(context.Context, *DeleteInstanceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInstance not implemented")
}
func (UnimplementedDaemonServiceServer) ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedDaemonServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*Instance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedDaemonServiceServer) GetInstanceLogs(*GetInstanceLogsRequest, grpc.ServerStreamingServer[InstanceLogChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetInstanceLogs not implemented")
}
func (UnimplementedDaemonServiceServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedDaemonServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedDaemonServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedDaemonServiceServer) RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*Instance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreSnapshot not implemented")
}
func (UnimplementedDaemonServiceServer) ExecInstance(grpc.BidiStreamingServer[ExecInstanceRequest, ExecInstanceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExecInstance not implemented")
}
func (UnimplementedDaemonServiceServer) CopyToInstance(grpc.ClientStreamingServer[CopyToInstanceRequest, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method CopyToInstance not implemented")
}
func (UnimplementedDaemonServiceServer) CopyFromInstance(*CopyFromInstanceRequest, grpc.ServerStreamingServer[CopyFromInstanceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CopyFromInstance not implemented")
}
func (UnimplementedDaemonServiceServer) CreateNetwork(context.Context, *CreateNetworkRequest) (*Network, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNetwork not implemented")
}
func (UnimplementedDaemonServiceServer) ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNetworks not implemented")
}
func (UnimplementedDaemonServiceServer) GetNetwork(context.Context, *GetNetworkRequest) (*Network, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetwork not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteNetwork(context.Context, *DeleteNetworkRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNetwork not implemented")
}
func (UnimplementedDaemonServiceServer) ListNetworkAllocations(context.Context, *ListNetworkAllocationsRequest) (*ListNetworkAllocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNetworkAllocations not implemented")
}
func (UnimplementedDaemonServiceServer) CreateVolume(context.Context, *CreateVolumeRequest) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedDaemonServiceServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedDaemonServiceServer) GetVolume(context.Context, *GetVolumeRequest) (*Volume, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolume not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteVolume(context.Context, *DeleteVolumeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedDaemonServiceServer) PullImage(*PullImageRequest, grpc.ServerStreamingServer[PullImageProgress]) error {
	return status.Errorf(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedDaemonServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedDaemonServiceServer) GetImage(context.Context, *GetImageRequest) (*Image, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImage not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteImage(context.Context, *DeleteImageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteImage not implemented")
}
func (UnimplementedDaemonServiceServer) PruneImages(context.Context, *PruneImagesRequest) (*PruneImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PruneImages not implemented")
}
func (UnimplementedDaemonServiceServer) ImportKernel(context.Context, *ImportKernelRequest) (*Kernel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportKernel not implemented")
}
func (UnimplementedDaemonServiceServer) ListKernels(context.Context, *ListKernelsRequest) (*ListKernelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKernels not implemented")
}
func (UnimplementedDaemonServiceServer) GetKernel(context.Context, *GetKernelRequest) (*Kernel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKernel not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteKernel(context.Context, *DeleteKernelRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKernel not implemented")
}
func (UnimplementedDaemonServiceServer) GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostInfo not implemented")
}
func (UnimplementedDaemonServiceServer) GetResources(context.Context, *GetResourcesRequest) (*GetResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResources not implemented")
}
func (UnimplementedDaemonServiceServer) GetEvents(*GetEventsRequest, grpc.ServerStreamingServer[GetEventsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue() {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call pancis, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_UpdateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).UpdateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_UpdateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).UpdateInstance(ctx, req.(*UpdateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RenameInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RenameInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RenameInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RenameInstance(ctx, req.(*RenameInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartInstance(ctx, req.(*StartInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopInstance(ctx, req.(*StopInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_PauseInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).PauseInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_PauseInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).PauseInstance(ctx, req.(*PauseInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ResumeInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ResumeInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ResumeInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ResumeInstance(ctx, req.(*ResumeInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteInstance(ctx, req.(*DeleteInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetInstanceLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetInstanceLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).GetInstanceLogs(m, &grpc.GenericServerStream[GetInstanceLogsRequest, InstanceLogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_GetInstanceLogsServer = grpc.ServerStreamingServer[InstanceLogChunk]

func _DaemonService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RestoreSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RestoreSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RestoreSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RestoreSnapshot(ctx, req.(*RestoreSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ExecInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DaemonServiceServer).ExecInstance(&grpc.GenericServerStream[ExecInstanceRequest, ExecInstanceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_ExecInstanceServer = grpc.BidiStreamingServer[ExecInstanceRequest, ExecInstanceResponse]

func _DaemonService_CopyToInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DaemonServiceServer).CopyToInstance(&grpc.GenericServerStream[CopyToInstanceRequest, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_CopyToInstanceServer = grpc.ClientStreamingServer[CopyToInstanceRequest, emptypb.Empty]

func _DaemonService_CopyFromInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CopyFromInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).CopyFromInstance(m, &grpc.GenericServerStream[CopyFromInstanceRequest, CopyFromInstanceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_CopyFromInstanceServer = grpc.ServerStreamingServer[CopyFromInstanceResponse]

func _DaemonService_CreateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CreateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CreateNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CreateNetwork(ctx, req.(*CreateNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListNetworks(ctx, req.(*ListNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetNetwork(ctx, req.(*GetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteNetwork(ctx, req.(*DeleteNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListNetworkAllocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworkAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListNetworkAllocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListNetworkAllocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListNetworkAllocations(ctx, req.(*ListNetworkAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetVolume(ctx, req.(*GetVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteVolume(ctx, req.(*DeleteVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_PullImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).PullImage(m, &grpc.GenericServerStream[PullImageRequest, PullImageProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_PullImageServer = grpc.ServerStreamingServer[PullImageProgress]

func _DaemonService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetImage(ctx, req.(*GetImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteImage(ctx, req.(*DeleteImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_PruneImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).PruneImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_PruneImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).PruneImages(ctx, req.(*PruneImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ImportKernel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportKernelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ImportKernel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ImportKernel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ImportKernel(ctx, req.(*ImportKernelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListKernels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKernelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListKernels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListKernels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListKernels(ctx, req.(*ListKernelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetKernel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKernelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetKernel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetKernel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetKernel(ctx, req.(*GetKernelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteKernel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKernelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteKernel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteKernel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteKernel(ctx, req.(*DeleteKernelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetHostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetHostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetHostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetHostInfo(ctx, req.(*GetHostInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetResources(ctx, req.(*GetResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).GetEvents(m, &grpc.GenericServerStream[GetEventsRequest, GetEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_GetEventsServer = grpc.ServerStreamingServer[GetEventsResponse]

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dicerd.v1.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInstance",
			Handler:    _DaemonService_CreateInstance_Handler,
		},
		{
			MethodName: "UpdateInstance",
			Handler:    _DaemonService_UpdateInstance_Handler,
		},
		{
			MethodName: "RenameInstance",
			Handler:    _DaemonService_RenameInstance_Handler,
		},
		{
			MethodName: "StartInstance",
			Handler:    _DaemonService_StartInstance_Handler,
		},
		{
			MethodName: "StopInstance",
			Handler:    _DaemonService_StopInstance_Handler,
		},
		{
			MethodName: "PauseInstance",
			Handler:    _DaemonService_PauseInstance_Handler,
		},
		{
			MethodName: "ResumeInstance",
			Handler:    _DaemonService_ResumeInstance_Handler,
		},
		{
			MethodName: "DeleteInstance",
			Handler:    _DaemonService_DeleteInstance_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _DaemonService_ListInstances_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _DaemonService_GetInstance_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _DaemonService_CreateSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _DaemonService_ListSnapshots_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _DaemonService_GetSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _DaemonService_DeleteSnapshot_Handler,
		},
		{
			MethodName: "RestoreSnapshot",
			Handler:    _DaemonService_RestoreSnapshot_Handler,
		},
		{
			MethodName: "CreateNetwork",
			Handler:    _DaemonService_CreateNetwork_Handler,
		},
		{
			MethodName: "ListNetworks",
			Handler:    _DaemonService_ListNetworks_Handler,
		},
		{
			MethodName: "GetNetwork",
			Handler:    _DaemonService_GetNetwork_Handler,
		},
		{
			MethodName: "DeleteNetwork",
			Handler:    _DaemonService_DeleteNetwork_Handler,
		},
		{
			MethodName: "ListNetworkAllocations",
			Handler:    _DaemonService_ListNetworkAllocations_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _DaemonService_CreateVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _DaemonService_ListVolumes_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _DaemonService_GetVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _DaemonService_DeleteVolume_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _DaemonService_ListImages_Handler,
		},
		{
			MethodName: "GetImage",
			Handler:    _DaemonService_GetImage_Handler,
		},
		{
			MethodName: "DeleteImage",
			Handler:    _DaemonService_DeleteImage_Handler,
		},
		{
			MethodName: "PruneImages",
			Handler:    _DaemonService_PruneImages_Handler,
		},
		{
			MethodName: "ImportKernel",
			Handler:    _DaemonService_ImportKernel_Handler,
		},
		{
			MethodName: "ListKernels",
			Handler:    _DaemonService_ListKernels_Handler,
		},
		{
			MethodName: "GetKernel",
			Handler:    _DaemonService_GetKernel_Handler,
		},
		{
			MethodName: "DeleteKernel",
			Handler:    _DaemonService_DeleteKernel_Handler,
		},
		{
			MethodName: "GetHostInfo",
			Handler:    _DaemonService_GetHostInfo_Handler,
		},
		{
			MethodName: "GetResources",
			Handler:    _DaemonService_GetResources_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetInstanceLogs",
			Handler:       _DaemonService_GetInstanceLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecInstance",
			Handler:       _DaemonService_ExecInstance_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CopyToInstance",
			Handler:       _DaemonService_CopyToInstance_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CopyFromInstance",
			Handler:       _DaemonService_CopyFromInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PullImage",
			Handler:       _DaemonService_PullImage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetEvents",
			Handler:       _DaemonService_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dicerd/v1/dicerd.proto",
}
